x-pg-replication-base: &pg-replication
  image: pg_replication:14
  build:
    context: .
  networks:
  - default


networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 192.168.55.0/24


services:
  primary:
    <<: *pg-replication

    volumes:
      - ./primary/data:/var/lib/postgresql/data:rw
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    command: -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'

    environment:
      - POSTGRES_PASSWORD=123@mudar

  replica:
    <<: *pg-replication

    volumes:
      - ./replica/data:/var/lib/postgresql/data:rw
      - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    command: -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'

    environment:
      - POSTGRES_PASSWORD=123@mudar

    depends_on:
      - primary
